---
- name: Install Mise
  yay:
    name: mise
    state: present

- name: Install ASDF
  yay:
    name: asdf-vm
    state: present

- name: Install programming languages with Mise
  shell: |
    mise add python
    mise add ruby
    mise add go
    mise add nodejs
    mise add lua
    mise add java
    mise add scala
    mise add haskell
    mise add lisp
    mise add racket
  args:
    executable: /bin/bash

- name: Install ASDF plugins
  shell: |
    asdf plugin-add python
    asdf plugin-add ruby
    asdf plugin-add golang
    asdf plugin-add nodejs
    asdf plugin-add lua
    asdf plugin-add java
    asdf plugin-add maven
    asdf plugin-add scala
    asdf plugin-add sbt
    asdf plugin-add haskell
    asdf plugin-add lisp
    asdf plugin-add racket
  args:
    executable: /bin/bash

- name: Install pipx packages
  pipx:
    name: "{{ item }}"
    state: present
  loop:
    - platformio
    - httpie
    - awscli
    - gcp
    - databricks-cli

