---
- name: Install sysadmin and hardening tools
  pacman:
    name:
      - etckeeper
      - firejail
      - timeshift
      - ufw
      - fail2ban
    state: present

- name: Configure UFW
  ufw:
    state: enabled
    policy: allow
    direction: incoming
    rule:
      - proto: tcp
        from: any
        to: any
        port: 22

- name: Enable Fail2Ban
  systemd:
    name: fail2ban
    enabled: true
    state: started

