---

- name: Ensure base-devel is installed (required for building AUR packages)
  pacman:
    name: base-devel
    state: present
  become: true

- name: Install yay (AUR helper)
  pacman:
    name: yay
    state: present
  become: true

- name: Install google-drive-ocamlfuse from AUR
  community.general.pacman:
    name: google-drive-ocamlfuse
    state: present
    use: yay
  become: true
  when: google_drive_install

- name: Create Google Drive mount point
  file:
    path: "{{ google_drive_mount_point }}"
    state: directory
    owner: "{{ cloud_storage_user }}"
    group: "{{ cloud_storage_user }}"
  when: google_drive_install

- name: Install Dropbox from AUR
  community.general.pacman:
    name: dropbox
    state: present
    use: yay
  become: true
  when: dropbox_install

- name: Install Tarsnap from AUR
  community.general.pacman:
    name: tarsnap
    state: present
    use: yay
  become: true
  when: tarsnap_install

