---
- name: Install KDE
  include_tasks: kde.yml
  when: "'kde' in desktop_environment"

- name: Install GNOME
  include_tasks: gnome.yml
  when: "'gnome' in desktop_environment"

- name: Install XMonad
  include_tasks: xmonad.yml
  when: "'xmonad' in desktop_environment"

- name: Install Qtile
  include_tasks: qtile.yml
  when: "'qtile' in desktop_environment"

