---
- name: Install XMonad and utilities
  pacman:
    name:
      - xmonad
      - xmonad-contrib
      - xmobar
      - dmenu
      - xdotool
      - picom
      - feh
      - i3lock
      - rofi
      - eww
      - polybar
    state: present
