---
# in case i want to restrict on arch
- name: Check distribution is supported
  ansible.builtin.assert:
    that: ansible_distribution == "Archlinux"
    fail_msg: "Distribution '{{ ansible_distribution }}' is not supported."
    success_msg: "Arch detected!"
