---
- name: Install KDE Plasma
  pacman:
    name:
      - plasma
      - kde-applications-meta
      - konsole
      - dolphin
      - sddm
    state: present

- name: Enable SDDM service for KDE
  systemd:
    name: sddm
    enabled: true
    state: started

