---
- name: Install XMonad and utilities
  pacman:
    name:
      - xmonad
      - xmonad-contrib
      - xmobar
      - dmenu
    state: present

- name: Configure XMonad
  copy:
    src: xmonad.hs
    dest: ~/.xmonad/xmonad.hs
  notify: restart_xmonad

- name: Start XMonad with X session
  shell: echo "exec xmonad" > ~/.xinitrc

- name: Restart XMonad
  systemd:
    name: xmonad
    state: restarted
  notify: restart_xmonad

handlers:
  - name: restart_xmonad
    command: xmonad --restart

