---
extends: default

ignore: |
    .github/workflows/main.yml

rules:
  braces:
    level: warning
    max-spaces-inside: 1
  line-length: disable
  truthy:
    allowed-values:
      - "yes"
      - "true"
      - "no"
      - "false"
